name: cstore
description: Vyatsu Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Gelasio
      fonts:
        - asset: assets/fonts/Gelasio-Regular.ttf
          weight: 400
        - asset: assets/fonts/Gelasio-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Gelasio-Bold.ttf
          weight: 700
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NunitoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NunitoSans-Bold.ttf
          weight: 700
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Regular.ttf
          weight: 400
        - asset: assets/fonts/Merriweather-Bold.ttf
          weight: 700
